[package]
name = "adventofcode"
version = "0.1.0"
edition = "2021"

[[bin]]
name="2023-1a"
path = "2023/01a.rs"

[[bin]]
name="2023-1b"
path = "2023/01b.rs"

[dependencies]
phf = { version = "0.11", features = ["macros"] }
regex = "1.10.2"
